### ISSUE TITLE
about cohesion-score

### ISSUE THREAD

**Issue by zdgithub** [UVa-NLP/HEDGE#1]
Thanks for your interesting work. 
I have some questions about the detail of the proposed cohesion-score for reproduction. 
- As said in the paper, given an important text span $x_{(a,b]}$, you randomly pick a position in the word sequence excluding $x_{(a,b]}$ and insert a word back. So I wonder which word you will insert back? Is it the text span $x_{(a,b]}$?
- And the above process will be repeated until a shuffled version is constructed. How do you identify the termination of the process, that is, when shall we decide that a shuffled version is constructed?

Sincerely hope for your reply. Thank you!

**Comment by HanjieChen** [comment]
> Thanks for your interesting work.
> I have some questions about the detail of the proposed cohesion-score for reproduction.
> 
> * As said in the paper, given an important text span $x_{(a,b]}$, you randomly pick a position in the word sequence excluding $x_{(a,b]}$ and insert a word back. So I wonder which word you will insert back? Is it the text span $x_{(a,b]}$?
> * And the above process will be repeated until a shuffled version is constructed. How do you identify the termination of the process, that is, when shall we decide that a shuffled version is constructed?
> 
> Sincerely hope for your reply. Thank you!

**Comment by HanjieChen** [comment]
Hi,

- Yes, we insert every word in the text span back with a random position.

- We repeat this process until all words in the text span are inserted back, and obtain a shuffled version.

**Comment by zdgithub** [comment]
I got it. Thank you!
